
version: '3'

services:

  fave-app:
    container_name: fave-app
    restart: always
    expose:
      - 3030
    ports:
      - "3030:3030"
    build:
      context: .
      dockerfile: Dockerfile
    image: rjmasikome/fave-app