---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: fave-app
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: fave-app
        component: fave-app
    spec:
      containers:
        - name: fave-app
          image: localhost:5000/fave-app:latest
          ports:
            - containerPort: 3030

---
apiVersion: v1
kind: Service
metadata:
  name: fave-app
  labels:
    app: fave-app
    component: fave-app
spec:
  ports:
    - port: 3030
      name: http-port
      nodePort: 30080
      targetPort: 3030
      protocol: TCP
  selector:
    app: fave-app
    component: fave-app
  type: NodePort

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: fave-app
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: local.mysneakers.com
    http:
      paths:
      - path: /
        backend:
          serviceName: fave-app
          servicePort: 3030